### ISSUE TITLE
C++ project

### ISSUE THREAD

**Issue by Trance-Paradox** [ndabas/pico-setup-windows#11]
After creating the project with ***Pico Project Generator*** and selecting all C++ options under ***Code Options*** I opened up the project on vscode from pico console. When I build the project in release mode it does not generate uf2 or even the hex file.

![image](https://user-images.githubusercontent.com/54877610/121871808-2a77ab80-cd22-11eb-8a95-4aab1c6724e4.png)

**Comment by ndabas** [comment]
It seems that CMake has generated the build files but did not compile them. On the command line, I would do this:

```
cd build
cmake -G "NMake Makefiles" ..
nmake
```

Unfortunately I don't have much experience with configuring VS Code properly to do this -- I suggest that you ask in the [forum](https://www.raspberrypi.org/forums/viewforum.php?f=144), and if you feel you have found a bug in the generated configuration -- you can open an issue in the [pico-project-generator](https://github.com/raspberrypi/pico-project-generator) repo.

It looks like you have been able to install the environment properly -- so this isn't an issue with this project (pico-setup-windows).

**Comment by Trance-Paradox** [comment]
> It seems that CMake has generated the build files but did not compile them. On the command line, I would do this:
> 
> ```
> cd build
> cmake -G "NMake Makefiles" ..
> nmake
> ```
> 
> Unfortunately I don't have much experience with configuring VS Code properly to do this -- I suggest that you ask in the [forum](https://www.raspberrypi.org/forums/viewforum.php?f=144), and if you feel you have found a bug in the generated configuration -- you can open an issue in the [pico-project-generator](https://github.com/raspberrypi/pico-project-generator) repo.
> 
> It looks like you have been able to install the environment properly -- so this isn't an issue with this project (pico-setup-windows).

Seems they only currently support c projects. I will try to create an issue in the project creator

**Comment by ndabas** [comment]
Closing as there is no further action in pico-setup-windows.
