### ISSUE TITLE
build almost works and fails

### ISSUE THREAD

**Issue by Geekume** [ndabas/pico-setup-windows#13]
I tried running the command  .\build.ps1 .\x64.json -MSYS2Path ~\Downloads\msys64 in powershell and it did its stuff until it gave me an error exec : Command ' & "$MSYS2Path\usr\bin\bash" -leo pipefail -c "$cmd" ' exited with c
At C:\Users\tjsun\Downloads\pico-setup-windows\build.ps1:94 char:3
+   exec { & "$MSYS2Path\usr\bin\bash" -leo pipefail -c "$cmd" }
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,exec

after checking whether we are cross compiling...

someone led  me here becuase i was having compile issues with pico and vs code and the errors from it still are there despite even redirecting the path to the pico-sdk within the folder of the setup 

it gives me stuff like:

[build] C:\Users\tjsun\Downloads\pico-setup-windows\pico-sdk\src\rp2_common\hardware_base\include/hardware/address_mapped.h:72:68: error: 'uintptr_t' undeclared (first use in this function); did you mean 'uint64_t'?
[build]    72 | #define hw_set_alias_untyped(addr) ((void *)(REG_ALIAS_SET_BITS | (uintptr_t)(addr)))
[build]       |                                                                    ^~~~~~~~~
[build] C:\Users\tjsun\Downloads\pico-setup-windows\pico-sdk\src\rp2_common\hardware_base\include/hardware/address_mapped.h:88:19: note: in expansion of macro 'hw_set_alias_untyped'
[build]    88 |     *(io_rw_32 *) hw_set_alias_untyped((volatile void *) addr) = mask;
[build]       |                   ^~~~~~~~~~~~~~~~~~~~
[build] C:\Users\tjsun\Downloads\pico-setup-windows\pico-sdk\src\rp2_common\hardware_base\include/hardware/address_mapped.h: In function 'hw_clear_bits':
[build] C:\Users\tjsun\Downloads\pico-setup-windows\pico-sdk\src\rp2_common\hardware_base\include/hardware/address_mapped.h:73:70: error: 'uintptr_t' undeclared (first use in this function); did you mean 'uint64_t'?
[build]    73 | #define hw_clear_alias_untyped(addr) ((void *)(REG_ALIAS_CLR_BITS | (uintptr_t)(addr)))
[build]       |                                                                      ^~~~~~~~~
[build] C:\Users\tjsun\Downloads\pico-setup-windows\pico-sdk\src\rp2_common\hardware_base\include/hardware/address_mapped.h:98:19: note: in expansion of macro 'hw_clear_alias_untyped'
[build]    98 |     *(io_rw_32 *) hw_clear_alias_untyped((volatile void *) addr) = mask;
[build]       |                   ^~~~~~~~~~~~~~~~~~~~~~
[build] C:\Users\tjsun\Downloads\pico-setup-windows\pico-sdk\src\rp2_common\hardware_base\include/hardware/address_mapped.h: In function 'hw_xor_bits':
[build] C:\Users\tjsun\Downloads\pico-setup-windows\pico-sdk\src\rp2_common\hardware_base\include/hardware/address_mapped.h:74:68: error: 'uintptr_t' undeclared (first use in this function); did you mean 'uint64_t'?
[build]    74 | #define hw_xor_alias_untyped(addr) ((void *)(REG_ALIAS_XOR_BITS | (uintptr_t)(addr)))
[build]       |                                                                    ^~~~~~~~~
[build] C:\Users\tjsun\Downloads\pico-setup-windows\pico-sdk\src\rp2_common\hardware_base\include/hardware/address_mapped.h:108:19: note: in expansion of macro 'hw_xor_alias_untyped'
[build]   108 |     *(io_rw_32 *) hw_xor_alias_untyped((volatile void *) addr) = mask;
[build]       |                   ^~~~~~~~~~~~~~~~~~~~
[build] In file included from C:\Users\tjsun\Downloads\pico-setup-windows\pico-sdk\src\common\pico_stdlib\include/pico/stdlib.h:14,
[build]                  from C:\Users\tjsun\Desktop\folder\main.c:2:
[build] C:\Users\tjsun\Downloads\pico-setup-windows\pico-sdk\src\rp2_common\hardware_uart\include/hardware/uart.h: In function 'uart_get_instance':
[build] C:\Users\tjsun\Downloads\pico-setup-windows\pico-sdk\src\rp2_common\hardware_uart\include/hardware/uart.h:105:5: warning: implicit declaration of function 'static_assert'; did you mean 'hard_assert'? [-Wimplicit-function-declaration]
[build]   105 |     static_assert(NUM_UARTS == 2, "");
[build]       |     ^~~~~~~~~~~~~
[build]       |     hard_assert
[build] NMAKE : fatal error U1077: 'C:\PROGRA~2\GNUARM~1\102020~1\bin\AR19DD~1.EXE' : return code '0x1'
[build] Stop.
[build] NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX86\x86\nmake.exe"' : return code '0x2'
[build] Stop.
[build] NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX86\x86\nmake.exe"' : return code '0x2'
[build] Stop.
[build] Build finished with exit code 2 

would love enlightenment on the situation 

-geekume

**Comment by ndabas** [comment]
The `build.ps1` script is for building this installer itself, you do not need to run it as a user of the Pico SDK. You can download a compiled release from the [releases section](https://github.com/ndabas/pico-setup-windows/releases).

Regarding the build issues, the [Pico SDK forum](https://www.raspberrypi.org/forums/viewforum.php?f=145) is the best place to ask, there are plenty of knowledgeable people there with deep knowledge of the SDK (including the authors.)

I'm closing this issue as it is not related to the installer itself. If you feel there was a problem with the installer, please open a new issue with the installer-related issue details.
