### ISSUE TITLE
Install stalls if newer version of git installed

### ISSUE THREAD

**Issue by N0g00dnam3s** [ndabas/pico-setup-windows#14]
I had installed git 2.33, the installing asked if I wanted to downgrade to 2.32.02 I said no and the installer did not seem to progress

**Comment by ndabas** [comment]
Thanks for the bug report! I'll look into how this can be mitigated.

**Comment by JamesWGT3** [comment]
I also have the above issue

**Comment by ndabas** [comment]
I have added a fix according to the info from [this commit](https://github.com/git-for-windows/build-extra/commit/c7bc72a157960ee9eef644141f116060c6c31c14). This _should_ work but I honestly do not have the resources to do extensive tests. Please re-open this issue or create a new one if anyone sees this issue with v0.3.4 or later.
