### ISSUE TITLE
VS2019 2019 install failed... 

### ISSUE THREAD

**Issue by Nikpesu** [ndabas/pico-setup-windows#19]
I tried to install x64 and x86 and both give me the same error.
![Screenshot_1](https://user-images.githubusercontent.com/92652074/151161321-3d5f62f2-73be-4033-8557-695d03198c5e.png)

**Comment by kefeur** [comment]
This is also a problem for me. But for me, python doesn't install.

**Comment by Nikpesu** [comment]
> This is also a problem for me. But for me, python doesn't install.

I got it running, you just need to exclude python from install(begining of instalation), i think that hapends when you already have installed some program and it tries to install again with this utility.
