### ISSUE TITLE
Installation of Build Tools for Visual Studio 2019 failed

### ISSUE THREAD

**Issue by azataiot** [ndabas/pico-setup-windows#20]
![image](https://user-images.githubusercontent.com/8280770/156894597-24ef1542-f410-4a5a-939b-7036497440f7.png)

Windows 11, Version 21H2 Os Build 22000.493

**Comment by byt3c** [comment]
It helped me to run this as administrator, but then extensions are not visible... Does not work for me either.

**Comment by ElectroBoy404NotFound** [comment]
windows 11 is having problems,working on windows 10

**Comment by w9ran** [comment]
Install fails:   normal mode, as Admin, x64, x86.  All fail.  Here's the detailed list of steps before it locks up the installation window - so can't copy/paste but here is a screen grab:

https://upload.picpaste.me/image/hkO3T

Appreciate any suggestions, thanks.

**Comment by ndabas** [comment]
Try the new release available from Raspberry Pi:
https://github.com/raspberrypi/pico-setup-windows/releases/latest

The Visual Studio dependency has been eliminated now, so this should not be a problem anymore.
