### ISSUE TITLE
Not digitally Signed.

### ISSUE THREAD

**Issue by jtannenba** [ndabas/pico-setup-windows#21]
This did not want to run on my Windows 11 machine.  Not digitally signed.  Had to set-executionpolicy. A true pain.

.\build.ps1 : File D:\Documents\Pico\pico-setup-windows-master\build.ps1 cannot be loaded. The file
D:\Documents\Pico\pico-setup-windows-master\build.ps1 is not digitally signed. You cannot run this script on the
current system. For more information about running scripts and setting execution policy, see about_Execution_Polic
https:/go.microsoft.com/fwlink/?LinkID=135170

**Comment by ndabas** [comment]
Running a well-documented first-party one-line command is "a true pain"? You do not need to run this script as an end user. If you want to do some development work on the project, `Set-ExecutionPolicy` is standard procedure for PowerShell development.

Closing this issue as no further action is needed.

**Comment by jtannenba** [comment]
Not if you are not a powershell user.  
    On Tuesday, May 3, 2022, 01:20:53 AM MST, Nikhil Dabas ***@***.***> wrote:  
 
 


Running a well-documented first-party one-line command is "a true pain"? You do not need to run this script as an end user. If you want to do some development work on the project, Set-ExecutionPolicy is standard procedure for PowerShell development.

Closing this issue as no further action is needed.

**Comment by jtannenba** [comment]
Ran in a powershell as admin:
After quite awhile, got this:

Command ' & "$MSYS2Path\usr\bin\bash" -leo pipefail -c "$cmd" ' exited with code 2At D:\Documents\Pico\pico-setup-windows-master\common.ps1:39 char:7+       throw "Command '$cmd' exited with code $LASTEXITCODE"+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : OperationStopped: (Command ' & "$M...ted with code 2:String) [], RuntimeException    + FullyQualifiedErrorId : Command ' & "$MSYS2Path\usr\bin\bash" -leo pipefail -c "$cmd" ' exited with code 2

So, does that mean the whole thing is bad?  Is there a way to recover?
Joe
    On Tuesday, May 3, 2022, 01:20:53 AM MST, Nikhil Dabas ***@***.***> wrote:  
 
 


Running a well-documented first-party one-line command is "a true pain"? You do not need to run this script as an end user. If you want to do some development work on the project, Set-ExecutionPolicy is standard procedure for PowerShell development.

Closing this issue as no further action is needed.

**Comment by jtannenba** [comment]
Sorry, I should have included:  Windows11 home 
The error appears to be syntax errors on a compile:
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -D__USE_MINGW_ANSI_STDIO -I./src -I./src -I./src/helper -DPKGDATADIR=\"/mingw64/share/openocd\" -DBINDIR=\"/mingw64/bin\" -I./jimtcl -I./jimtcl  -Wall -Wstrict-prototypes -Wformat-security -Wshadow -Wextra -Wno-unused-parameter -Wbad-function-cast -Wcast-align -Wredundant-decls -Wpointer-arith -Werror -g -O2 -MT src/flash/nor/pic32mx.lo -MD -MP -MF $depbase.Tpo -c -o src/flash/nor/pic32mx.lo src/flash/nor/pic32mx.c &&\mv -f $depbase.Tpo $depbase.Plolibtool: compile:  gcc -DHAVE_CONFIG_H -I. -D__USE_MINGW_ANSI_STDIO -I./src -I./src -I./src/helper -DPKGDATADIR=\"/mingw64/share/openocd\" -DBINDIR=\"/mingw64/bin\" -I./jimtcl -I./jimtcl -Wall -Wstrict-prototypes -Wformat-security -Wshadow -Wextra -Wno-unused-parameter -Wbad-function-cast -Wcast-align -Wredundant-decls -Wpointer-arith -Werror -g -O2 -MT src/flash/nor/nrf5.lo -MD -MP -MF src/flash/nor/.deps/nrf5.Tpo -c src/flash/nor/nrf5.c -o src/flash/nor/nrf5.olibtool: compile:  gcc -DHAVE_CONFIG_H -I. -D__USE_MINGW_ANSI_STDIO -I./src -I./src -I./src/helper -DPKGDATADIR=\"/mingw64/share/openocd\" -DBINDIR=\"/mingw64/bin\" -I./jimtcl -I./jimtcl -Wall -Wstrict-prototypes -Wformat-security -Wshadow -Wextra -Wno-unused-parameter -Wbad-function-cast -Wcast-align -Wredundant-decls -Wpointer-arith -Werror -g -O2 -MT src/flash/nor/numicro.lo -MD -MP -MF src/flash/nor/.deps/numicro.Tpo -c src/flash/nor/numicro.c -o src/flash/nor/numicro.olibtool: compile:  gcc -DHAVE_CONFIG_H -I. -D__USE_MINGW_ANSI_STDIO -I./src -I./src -I./src/helper -DPKGDATADIR=\"/mingw64/share/openocd\" -DBINDIR=\"/mingw64/bin\" -I./jimtcl -I./jimtcl -Wall -Wstrict-prototypes -Wformat-security -Wshadow -Wextra -Wno-unused-parameter -Wbad-function-cast -Wcast-align -Wredundant-decls -Wpointer-arith -Werror -g -O2 -MT src/flash/nor/ocl.lo -MD -MP -MF src/flash/nor/.deps/ocl.Tpo -c src/flash/nor/ocl.c -o src/flash/nor/ocl.olibtool: compile:  gcc -DHAVE_CONFIG_H -I. -D__USE_MINGW_ANSI_STDIO -I./src -I./src -I./src/helper -DPKGDATADIR=\"/mingw64/share/openocd\" -DBINDIR=\"/mingw64/bin\" -I./jimtcl -I./jimtcl -Wall -Wstrict-prototypes -Wformat-security -Wshadow -Wextra -Wno-unused-parameter -Wbad-function-cast -Wcast-align -Wredundant-decls -Wpointer-arith -Werror -g -O2 -MT src/flash/nor/pic32mx.lo -MD -MP -MF src/flash/nor/.deps/pic32mx.Tpo -c src/flash/nor/pic32mx.c -o src/flash/nor/pic32mx.osrc/flash/nor/numicro.c: In function 'numicro_fmc_cmd':src/flash/nor/numicro.c:1244:17: error: this 'if' clause does not guard... [-Werror=misleading-indentation] 1244 |                 if (retval != ERROR_OK)      |                 ^~In file included from ./src/flash/common.h:21,                 from src/flash/nor/core.h:25,                 from src/flash/nor/imp.h:24,                 from src/flash/nor/numicro.c:32:./src/helper/log.h:119:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'  119 |         do { \      |         ^~./src/helper/log.h:119:9: note: in definition of macro 'LOG_DEBUG'  119 |         do { \      |         ^~src/flash/nor/numicro.c: In function 'numicro_erase':src/flash/nor/numicro.c:1513:25: error: this 'if' clause does not guard... [-Werror=misleading-indentation] 1513 |                         if (retval != ERROR_OK)      |                         ^~In file included from ./src/flash/common.h:21,                 from src/flash/nor/core.h:25,                 from src/flash/nor/imp.h:24,                 from src/flash/nor/numicro.c:32:./src/helper/log.h:119:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'  119 |         do { \      |         ^~./src/helper/log.h:119:9: note: in definition of macro 'LOG_DEBUG'  119 |         do { \      |         ^~src/flash/nor/numicro.c: In function 'numicro_write':src/flash/nor/numicro.c:1602:33: error: this 'if' clause does not guard... [-Werror=misleading-indentation] 1602 |                                 if (retval != ERROR_OK)      |                                 ^~In file included from ./src/flash/common.h:21,                 from src/flash/nor/core.h:25,                 from src/flash/nor/imp.h:24,                 from src/flash/nor/numicro.c:32:./src/helper/log.h:119:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'  119 |         do { \      |         ^~./src/helper/log.h:119:9: note: in definition of macro 'LOG_DEBUG'  119 |         do { \      |         ^~depbase=`echo src/flash/nor/psoc4.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -D__USE_MINGW_ANSI_STDIO -I./src -I./src -I./src/helper -DPKGDATADIR=\"/mingw64/share/openocd\" -DBINDIR=\"/mingw64/bin\" -I./jimtcl -I./jimtcl  -Wall -Wstrict-prototypes -Wformat-security -Wshadow -Wextra -Wno-unused-parameter -Wbad-function-cast -Wcast-align -Wredundant-decls -Wpointer-arith -Werror -g -O2 -MT src/flash/nor/psoc4.lo -MD -MP -MF $depbase.Tpo -c -o src/flash/nor/psoc4.lo src/flash/nor/psoc4.c &&\mv -f $depbase.Tpo $depbase.Plocc1.exe: all warnings being treated as errorsmake[2]: *** [Makefile:3629: src/flash/nor/numicro.lo] Error 1make[2]: *** Waiting for unfinished jobs....libtool: compile:  gcc -DHAVE_CONFIG_H -I. -D__USE_MINGW_ANSI_STDIO -I./src -I./src -I./src/helper -DPKGDATADIR=\"/mingw64/share/openocd\" -DBINDIR=\"/mingw64/bin\" -I./jimtcl -I./jimtcl -Wall -Wstrict-prototypes -Wformat-security -Wshadow -Wextra -Wno-unused-parameter -Wbad-function-cast -Wcast-align -Wredundant-decls -Wpointer-arith -Werror -g -O2 -MT src/flash/nor/psoc4.lo -MD -MP -MF src/flash/nor/.deps/psoc4.Tpo -c src/flash/nor/psoc4.c -o src/flash/nor/psoc4.omake[2]: Leaving directory '/d/Documents/Pico/pico-setup-windows-master/build/openocd'make[1]: *** [Makefile:5318: all-recursive] Error 1make[1]: Leaving directory '/d/Documents/Pico/pico-setup-windows-master/build/openocd'make: *** [Makefile:2175: all] Error 2Command ' & "$MSYS2Path\usr\bin\bash" -leo pipefail -c "$cmd" ' exited with code 2At D:\Documents\Pico\pico-setup-windows-master\common.ps1:39 char:7+       throw "Command '$cmd' exited with code $LASTEXITCODE"+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : OperationStopped: (Command ' & "$M...ted with code 2:String) [], RuntimeException    + FullyQualifiedErrorId : Command ' & "$MSYS2Path\usr\bin\bash" -leo pipefail -c "$cmd" ' exited with code 2

I assume it is dead, no files in the bin directory?
    On Tuesday, May 3, 2022, 01:20:53 AM MST, Nikhil Dabas ***@***.***> wrote:  
 
 


Running a well-documented first-party one-line command is "a true pain"? You do not need to run this script as an end user. If you want to do some development work on the project, Set-ExecutionPolicy is standard procedure for PowerShell development.

Closing this issue as no further action is needed.
