### ISSUE TITLE
Installation fails on Windows 10

### ISSUE THREAD

**Issue by w9ran** [ndabas/pico-setup-windows#23]
I can't copy the text because the installer window locks up and closes when I click Cancel, but this is as far as it gets:

![image](https://user-images.githubusercontent.com/3194542/173920395-ead92faa-cfe9-449a-abda-1497117daf9a.png)

I would certainly appreciate help in resolving this.  I reset my Microsoft Store account after looking at a Collect log but that wasn't it.
Thanks.

**Comment by w9ran** [comment]
Here is a complete capture of the installation screen showing that the error  occurs with Build Tools for Visual Studio.   Can anyone tell why this is happening and how to fix it?    Probably something has changed in a directory or path?

![image](https://user-images.githubusercontent.com/3194542/177381132-54461b4b-5a18-4e12-b89f-acd47c687485.png)

**Comment by w9ran** [comment]
[install_log.txt](https://github.com/ndabas/pico-setup-windows/files/9048272/install_log.txt)

Here is the complete install.log file from failed installation.

**Comment by ndabas** [comment]
Thanks for the detailed notes and logs -- I'll take a look and see if I can figure something out, or if I need more log files.

**Comment by Acasmol** [comment]
Hello All!
I'm also having issues with installing on Window 10

All instalations go well, till the last steps whil running the CMD commands.

Any of the CMD excecuted, ends with:

`No se esperaba \Arm en este momento`


Attach the images:

![00001](https://user-images.githubusercontent.com/17996696/208225562-ccf73b90-c996-4a92-a5d9-f197ef26a2a8.JPG)
![00002](https://user-images.githubusercontent.com/17996696/208225564-212ec81c-2a5a-4440-80cb-ba20dd720c16.JPG)

**Comment by ndabas** [comment]
@Acasmol does your username (as used in the path which you have redacted in the screenshot) contain spaces or any non-latin characters by any chance?

**Comment by Acasmol** [comment]
Hello @ndabas !

No, doesnt contain any spaces or any non-latin characters.

But I already fixed!. It was not a problem related to the SDK, I was a problem that one of my routes in the PATH was pointing to a  folder that doesn't exist, removed that route and it works fine now.

This is issue was not open by me, I just take advantage and start writting here, but, can I close it?

**Comment by ndabas** [comment]
Hello @Acasmol, thanks for the investigation! I'll close this issue now.
