### ISSUE TITLE
Path Variable gets overwritten

### ISSUE THREAD

**Issue by Keksnet** [ndabas/pico-setup-windows#24]
Hey there,

after I installed the latest version my PATH environment variable was overwritten.
![grafik](https://user-images.githubusercontent.com/56829999/174494222-af2864c7-e349-4f6d-aff8-aa2ff662ab28.png)

Please try to fix it because I now have to recover my PATH variable.

Greetings from Germany

**Comment by ndabas** [comment]
This installer isn't doing anything to the PATH -- it seems the ARM GCC installer did something unexpected. Please file a bug in [that project](https://launchpad.net/gcc-arm-embedded) if this is still an issue.
