### ISSUE TITLE
openOCD compilation failes with error code 2

### ISSUE THREAD

**Issue by humfry** [ndabas/pico-setup-windows#25]
After fixing the the path to 'Doxygen' as it is obsolete, the compilation of the openOCD failes.

Just one error of many more that follow (could also be errors of errors):

`
src/flash/nor/numicro.c:1244:17: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
 1244 |                 if (retval != ERROR_OK)
      |                 ^~
In file included from ./src/flash/common.h:21,
                 from src/flash/nor/core.h:25,
                 from src/flash/nor/imp.h:24,
                 from src/flash/nor/numicro.c:32:
`

Don't know how to fix this.

Is this related to Windows only?

**Comment by ndabas** [comment]
This should be fixed now, because we are now using upstream OpenOCD instead of the Raspberry Pi fork for picoprobe.
