### ISSUE TITLE
Trying to get in touch...

### ISSUE THREAD

**Issue by ghollingworth** [ndabas/pico-setup-windows#26]
Hey, since github has no private comms system, been trying to get in touch...  Thought this might work instead!

Also tried twitter and LinkedIn but to no avail...  Can you email me at info@raspberrypi.com and say its for Gordon?

**Comment by ndabas** [comment]
Hi Gordon,

Not sure why the other platforms didn't get the message through, but I have sent an email to the info email address like you asked.

Best,
Nikhil.
