### ISSUE TITLE
 Installation of Build Tools for Visual Studio 2019 failed

### ISSUE THREAD

**Issue by xawel007** [ndabas/pico-setup-windows#34]
Unfortunately :
Build Tools for Visual Studio 2019 returned 0
Delete on reboot: C:\********
Installation of Build Tools for Visual Studio 2019 failed

**Comment by ndabas** [comment]
A new release is coming soon that eliminates the need to install Visual Studio entirely.

**Comment by ndabas** [comment]
Try the new release available from Raspberry Pi:
https://github.com/raspberrypi/pico-setup-windows/releases/latest

The Visual Studio dependency has been eliminated now, so this should not be a problem anymore.
